# Generated by Django 3.2.5 on 2021-11-06 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('stock_pcs', models.PositiveIntegerField()),
                ('price', models.FloatField()),
                ('shop_id', models.CharField(max_length=10)),
                ('vip', models.BooleanField()),
            ],
        ),
    ]
